language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE questioner_test;' -U postgres
  - export TEST_DB_URL="dbname='questioner_test'  user='' password='' host='localhost'"
  - export FLASK_ENV="testing"

script:
  - pytest --cov=app/
  - coveralls

after_success:
  - coveralls